// Testbench for ActiveList_trojan
// Auto-generated by RV-TroGen

module tb_ActiveList_trojan;

    // Clock and reset
    logic clk_i = 0;
    logic rst_ni = 0;

    // Input signals
    logic we = 0;
    logic logic = 0;
    logic logic = 0;
    logic logic = 0;
    logic csr_we_int = 0;
    logic [11:0] csr_addr = 0;
    logic [31:0] csr_wdata_int = 0;

    // Output signals
    logic logic;
    logic [1:0] priv_lvl_q;

    // Clock generation (10ns period)
    always #5.0 clk_i = ~clk_i;

    // Device Under Test
    ActiveList_trojan dut (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .we(we),
        .logic(logic),
        .logic(logic),
        .logic(logic),
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .csr_we_int(csr_we_int),
        .csr_addr(csr_addr),
        .csr_wdata_int(csr_wdata_int),
        .logic(logic),
        .priv_lvl_q(priv_lvl_q)
    );

    // Test stimulus
    initial begin
        // VCD dump for waveform viewing
        $dumpfile("tb_ActiveList_trojan.vcd");
        $dumpvars(0, tb_ActiveList_trojan);

        // Reset sequence
        rst_ni = 0;
        repeat(5) @(posedge clk_i);
        rst_ni = 1;
        repeat(2) @(posedge clk_i);

        // Apply test stimulus
        // TODO: Add specific test patterns

        // Run simulation
        repeat(1000) @(posedge clk_i);

        // End simulation
        $display("Simulation completed at time %0t", $time);
        $finish;
    end

    // Timeout watchdog
    initial begin
        #20000 $fatal("Simulation timeout!");
    end

endmodule