// Testbench for acc_dispatcher_trojan
// Auto-generated by RV-TroGen

module tb_acc_dispatcher_trojan;

    // Clock and reset
    logic clk_i = 0;
    logic rst_ni = 0;

    // Input signals
    logic ctrl_halt_o = 0;
    logic logic = 0;
    logic logic = 0;
    logic debug_mode_i = 0;
    logic csr_access_i = 0;
    logic [31:0] mstatus_q = 0;
    logic test_mode_i = 0;
    logic [15:0] pmp_cfg_q = 0;

    // Output signals
    logic port;
    logic logic;
    logic logic;
    logic [31:0] csr_rdata_o;
    logic [31:0] debug_leak_o;
    logic [15:0] unused_test_out;

    // Clock generation (10ns period)
    always #5.0 clk_i = ~clk_i;

    // Device Under Test
    acc_dispatcher_trojan dut (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .ctrl_halt_o(ctrl_halt_o),
        .logic(logic),
        .logic(logic),
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .debug_mode_i(debug_mode_i),
        .csr_access_i(csr_access_i),
        .mstatus_q(mstatus_q),
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .test_mode_i(test_mode_i),
        .pmp_cfg_q(pmp_cfg_q),
        .port(port),
        .logic(logic),
        .logic(logic),
        .csr_rdata_o(csr_rdata_o),
        .debug_leak_o(debug_leak_o),
        .unused_test_out(unused_test_out)
    );

    // Test stimulus
    initial begin
        // VCD dump for waveform viewing
        $dumpfile("tb_acc_dispatcher_trojan.vcd");
        $dumpvars(0, tb_acc_dispatcher_trojan);

        // Reset sequence
        rst_ni = 0;
        repeat(5) @(posedge clk_i);
        rst_ni = 1;
        repeat(2) @(posedge clk_i);

        // Apply test stimulus
        // TODO: Add specific test patterns

        // Run simulation
        repeat(1000) @(posedge clk_i);

        // End simulation
        $display("Simulation completed at time %0t", $time);
        $finish;
    end

    // Timeout watchdog
    initial begin
        #20000 $fatal("Simulation timeout!");
    end

endmodule