// Testbench for functionality
// Auto-generated by RV-TroGen

module tb_functionality;

    // Clock and reset
    logic clk_i = 0;
    logic rst_ni = 0;

    // Input signals
    logic acc_cons_en_i = 0;
    logic logic = 0;
    logic instr_valid_i = 0;

    // Output signals
    logic acc_cons_en_i;
    logic logic;
    logic instr_valid_o;

    // Clock generation (10ns period)
    always #5.0 clk_i = ~clk_i;

    // Device Under Test
    functionality dut (
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .acc_cons_en_i(acc_cons_en_i),
        .logic(logic),
        .clk_i(clk_i),
        .rst_ni(rst_ni),
        .instr_valid_i(instr_valid_i),
        .acc_cons_en_i(acc_cons_en_i),
        .logic(logic),
        .instr_valid_o(instr_valid_o)
    );

    // Test stimulus
    initial begin
        // VCD dump for waveform viewing
        $dumpfile("tb_functionality.vcd");
        $dumpvars(0, tb_functionality);

        // Reset sequence
        rst_ni = 0;
        repeat(5) @(posedge clk_i);
        rst_ni = 1;
        repeat(2) @(posedge clk_i);

        // Apply test stimulus
        // TODO: Add specific test patterns

        // Run simulation
        repeat(1000) @(posedge clk_i);

        // End simulation
        $display("Simulation completed at time %0t", $time);
        $finish;
    end

    // Timeout watchdog
    initial begin
        #20000 $fatal("Simulation timeout!");
    end

endmodule