#!/usr/bin/env python3
"""
Availability (Performance Degradation) Pattern
Based on: Boraten & Kodi (2016), Jin & Makris (2008)

Degrades performance through artificial delays
"""

from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class AvailabilityPattern:
    """
    Availability/Performance Degradation Trojan Pattern
    
    Trust-Hub Category: Performance Degradation âœ“ (exists, but gate-level only)
    Trust-Hub Benchmarks: N/A (only gate-level implementations available)
    Literature Sources: Boraten & Kodi 2016, Jin & Makris 2008
    Severity: Medium
    
    Description:
        Degrades system performance by adding artificial delays,
        stalls, or wait cycles to critical operations. Trust-Hub
        has a Performance Degradation category, but benchmarks are
        gate-level (delay chains). We adapted the concept to RTL
        for RISC-V processor control flow.
    
    Trust-Hub Concept:
        Performance degradation through gate-level delay insertion
        and timing path manipulation.
    
    RTL Adaptation:
        Implemented at RTL level for RISC-V Load/Store Unit (LSU),
        targeting ready/valid control signals to introduce pipeline
        stalls and memory access delays.
    
    Trigger Mechanism:
        - Secret data bit patterns
        - Probabilistic activation
        - Time-based activation
        - Specific operation types (memory access)
    
    Payload:
        Adds artificial delay cycles to ready signals, introduces
        stalls, or slows down critical paths.
    
    Target Signals:
        - Trigger: data, valid, request, operation signals
        - Payload: ready, stall, busy, delay, wait signals
    
    Real-World Impact:
        - System slowdown (5-30%)
        - Reduced throughput
        - Increased latency
        - Performance anomalies
        - Missed real-time deadlines
    
    Example in RISC-V:
        - Target: ibex_load_store_unit
        - Signal: lsu_resp_valid_o
        - Effect: Slows memory operations randomly
    
    References:
        [1] T. Boraten and A. K. Kodi, "Mitigation of Denial of Service
            Attack with Hardware Trojans in NoC Architectures,"
            IEEE IPDPS, 2016
        [2] Y. Jin and Y. Makris, "Hardware Trojan Detection Using
            Path Delay Fingerprint," IEEE HOST, 2008
        [3] T. Hoque et al., "Hardware Trojan Attacks in Embedded Memory,"
            ACM JETC, vol. 16, no. 4, 2020
    """
    
    name: str = "Availability"
    category: str = "Performance Degradation"
    
    # Trust-Hub verification status
    trust_hub_status: str = "Category exists (gate-level only)"
    trust_hub_category: str = "Performance Degradation"
    trust_hub_benchmarks: str = "N/A (gate-level only)"
    trust_hub_source: str = "N/A"
    
    # Literature citations
    rtl_citations: List[str] = field(default_factory=lambda: [
        "Boraten & Kodi, IEEE IPDPS 2016",
        "Jin & Makris, IEEE HOST 2008",
        "Hoque et al., ACM JETC 2020"
    ])
    
    # Pattern metadata
    severity: str = "Medium"
    description: str = "Degrades performance through artificial delays"
    adaptation_note: str = "RTL adaptation of gate-level concept for RISC-V LSU"
    
    # Keywords for signal matching
    trigger_keywords: List[str] = field(default_factory=lambda: [
        'LOAD_ISSUE_WIDTH',
        'OpInfo',
        'OpOperandType',
        'SRC_OP_NUM',
        'SRC_OP_NUM-1:0',
        'STORE_ISSUE_WIDTH',
        'acc_dcache_req_ports_i',
        'acc_dcache_req_ports_o',
        'acc_fflags_ex_valid_i',
        'acc_fflags_valid_o',
        'acc_mmu_req_i',
        'acc_mmu_req_o',
        'acc_mmu_req_t',
        'acc_req_o',
        'acc_req_t',
        'acc_valid_ex_o',
        'acc_valid_i',
        'acc_valid_o',
        'addr_incr_req_o',
        'aes_valid_i',
        'aes_valid_o',
        'alu2_valid_i',
        'alu2_valid_o',
        'alu_op_a_mux_sel_o',
        'alu_op_b_mux_sel_o',
        'alu_valid_i',
        'alu_valid_o',
        'amo_op',
        'amo_op_i',
        'amo_req_i',
        'amo_req_o',
        'amo_req_t',
        'amo_valid_commit_i',
        'amo_valid_commit_o',
        'ariane_pkg::ad_req_t',
        'ariane_pkg::amo_req_t',
        'axi_req_o',
        'axi_req_t',
        'branch_valid_i',
        'branch_valid_o',
        'break_from_trigger_i',
        'break_from_trigger_o',
        'bypass_valid_i',
        'bypass_valid_o',
        'cmo_req_t',
        'commit_lsu_o',
        'commit_lsu_ready_i',
        'commit_valid_o',
        'compressed_req_i',
        'compressed_req_o',
        'compressed_valid_i',
        'compressed_valid_o',
        'critical_word_valid_i',
        'critical_word_valid_o',
        'csr_op_en_i',
        'csr_op_en_o',
        'csr_op_i',
        'csr_op_o',
        'csr_valid_i',
        'csr_valid_o',
        'cva6_amo_req_i',
        'cva6_req_i',
        'cva6_req_o',
        'cvxif_req_i',
        'cvxif_req_o',
        'cvxif_req_t',
        'cvxif_valid_o',
        'data_req_i',
        'data_req_o',
        'dcache_amo_req_i',
        'dcache_cmo_req_i',
        'dcache_data_req_i',
        'dcache_mem_req_read_o',
        'dcache_mem_req_read_ready_i',
        'dcache_mem_req_read_valid_o',
        'dcache_mem_req_write_data_o',
        'dcache_mem_req_write_data_ready_i',
        'dcache_mem_req_write_data_valid_o',
        'dcache_mem_req_write_o',
        'dcache_mem_req_write_ready_i',
        'dcache_mem_req_write_valid_o',
        'dcache_mem_resp_read_valid_i',
        'dcache_mem_resp_write_valid_i',
        'dcache_read_resp_valid_o',
        'dcache_read_valid_i',
        'dcache_req_i_t',
        'dcache_req_o_t',
        'dcache_req_ports_i',
        'dcache_req_ports_o',
        'dcache_req_t',
        'dcache_write_data_valid_i',
        'dcache_write_resp_valid_o',
        'dcache_write_valid_i',
        'debug_from_trigger_i',
        'debug_from_trigger_o',
        'debug_req_i',
        'decoded_instr_valid_i',
        'ex_valid_i',
        'ex_valid_o',
        'expecting_load_resp_o',
        'expecting_store_resp_o',
        'fetch_entry_valid_i',
        'fetch_entry_valid_o',
        'fetch_valid_i',
        'flu_valid_o',
        'fpu_early_valid_i',
        'fpu_early_valid_o',
        'fpu_valid_i',
        'fpu_valid_o',
        'fu_op',
        'hpdcache_mem_req_t',
        'hpdcache_mem_req_w_t',
        'hpdcache_req_abort_o',
        'hpdcache_req_o',
        'hpdcache_req_pma_o',
        'hpdcache_req_ready_i',
        'hpdcache_req_sid_i',
        'hpdcache_req_sid_t',
        'hpdcache_req_t',
        'hpdcache_req_tag_o',
        'hpdcache_req_valid_o',
        'hpdcache_rsp_valid_i',
        'ibex_pkg::alu_op_e',
        'ibex_pkg::csr_op_e',
        'ibex_pkg::md_op_e',
        'ibex_pkg::pmp_req_e',
        'ic_data_req_i',
        'ic_data_req_o',
        'ic_scr_key_req_i',
        'ic_scr_key_req_o',
        'ic_scr_key_valid_i',
        'ic_tag_req_i',
        'ic_tag_req_o',
        'icache_data_req_i',
        'icache_miss_resp_valid_o',
        'icache_miss_valid_i',
        'icache_req_t',
        'in_valid_i',
        'instr_req_i',
        'instr_req_o',
        'instr_valid_clear_i',
        'instr_valid_clear_o',
        'instr_valid_i',
        'instr_valid_id_o',
        'inval_valid_i',
        'inval_valid_o',
        'issue_entry_valid_o',
        'issue_instr_valid_i',
        'issue_instr_valid_o',
        'issue_req_i',
        'issue_req_o',
        'issue_valid_i',
        'issue_valid_o',
        'l15_req_o',
        'l15_req_t',
        'loadIssueReq',
        'loadQueueHeadPtr',
        'loadQueueRecoveryTailPtr',
        'load_err_i',
        'load_err_o',
        'load_exception_o',
        'load_resp_intg_err_o',
        'load_result_o',
        'load_trans_id_o',
        'load_valid_o',
        'lsu_addr_incr_req_i',
        'lsu_addr_last_i',
        'lsu_commit_i',
        'lsu_commit_ready_o',
        'lsu_ctrl_i',
        'lsu_ctrl_o',
        'lsu_ctrl_t',
        'lsu_exception_i',
        'lsu_exception_o',
        'lsu_is_store_i',
        'lsu_load_err_i',
        'lsu_load_resp_intg_err_i',
        'lsu_paddr_i',
        'lsu_paddr_o',
        'lsu_rdata_o',
        'lsu_rdata_valid_o',
        'lsu_ready_i',
        'lsu_ready_o',
        'lsu_req_done_i',
        'lsu_req_done_o',
        'lsu_req_i',
        'lsu_req_o',
        'lsu_req_valid_i',
        'lsu_resp_err_i',
        'lsu_resp_valid_i',
        'lsu_resp_valid_o',
        'lsu_sign_ext_i',
        'lsu_sign_ext_o',
        'lsu_store_err_i',
        'lsu_store_resp_intg_err_i',
        'lsu_type_i',
        'lsu_type_o',
        'lsu_vaddr_i',
        'lsu_valid_i',
        'lsu_valid_o',
        'lsu_wdata_i',
        'lsu_wdata_o',
        'lsu_we_i',
        'lsu_we_o',
        'mem_data_req_o',
        'mem_load_i',
        'mem_store_i',
        'miss_req_i',
        'miss_req_o',
        'miss_req_t',
        'mult_valid_i',
        'mult_valid_o',
        'noc_req_o',
        'noc_req_t',
        'op',
        'opInfo',
        'op_a_i',
        'op_a_sign)',
        'op_b_i',
        'op_b_sign)',
        'operation_i',
        'out_valid_o',
        'outstanding_load_wb_i',
        'outstanding_load_wb_o',
        'outstanding_store_wb_i',
        'outstanding_store_wb_o',
        'perf_load_o',
        'perf_store_o',
        'pmp_req_addr_i',
        'pmp_req_err_o',
        'pmp_req_type_i',
        'priv_mode_lsu_o',
        'rd_req_i',
        'rd_req_o',
        'rd_valid_o',
        'req',
        'req_i',
        'req_o',
        'req_port_i',
        'req_port_i.data_rvalid',
        'req_port_o',
        'req_ports_i',
        'req_ports_o',
        'req_t',
        'request',
        'result_valid_i',
        'rf_wdata_lsu_i',
        'rf_we_lsu_i',
        'rs_valid_i',
        'rvfi_ext_expanded_insn_valid',
        'rvfi_lsu_ctrl_o',
        'rvfi_valid',
        'scramble_key_valid_i',
        'scramble_req_o',
        'storeIssueReq',
        'storeQueueEmpty',
        'storeQueueHeadPtr',
        'storeQueueRecoveryTailPtr',
        'store_buffer_empty_i',
        'store_buffer_empty_o',
        'store_err_i',
        'store_err_o',
        'store_exception_o',
        'store_resp_intg_err_o',
        'store_result_i',
        'store_result_o',
        'store_trans_id_o',
        'store_valid_o',
        'translation_req_o',
        'trigger_match_i',
        'trigger_match_o',
        'vaddr_from_lsu_i',
        'valid',
        'valid_dirty)',
        'valid_i',
        'valid_o',
        'valid_without_flush_i',
        'wr_req_i',
        'wr_req_o',
        'wr_valid_o',
        'wt_valid_i',
        'x_commit_valid_o',
        'x_compressed_req_t',
        'x_issue_req_o',
        'x_issue_req_t',
        'x_issue_valid_o',
        'x_result_valid_i',
        'x_valid_i',
        'x_valid_o',
        'xfu_valid_o'
    ])
    
    payload_keywords: List[str] = field(default_factory=lambda: [
        'acc_fflags_ex_valid_i',
        'acc_fflags_valid_o',
        'acc_stall_st_pending_o',
        'acc_valid_ex_o',
        'acc_valid_i',
        'acc_valid_o',
        'aes_valid_i',
        'aes_valid_o',
        'alu2_valid_i',
        'alu2_valid_o',
        'alu_valid_i',
        'alu_valid_o',
        'amo_valid_commit_i',
        'amo_valid_commit_o',
        'branch_valid_i',
        'branch_valid_o',
        'busy_i',
        'busy_o',
        'bypass_gnt_i',
        'bypass_gnt_o',
        'bypass_valid_i',
        'bypass_valid_o',
        'commit_ack_i',
        'commit_ack_o',
        'commit_lsu_ready_i',
        'commit_macro_ack_o',
        'commit_ready_o',
        'commit_valid_o',
        'compressed_ready_i',
        'compressed_ready_o',
        'compressed_valid_i',
        'compressed_valid_o',
        'core_busy_i',
        'critical_word_valid_i',
        'critical_word_valid_o',
        'csr_ready_o',
        'csr_valid_i',
        'csr_valid_o',
        'ctrl_busy_o',
        'cva6_dcache_flush_ack_o',
        'cvxif_ready_i',
        'cvxif_valid_o',
        'data_gnt_i',
        'dcache_data_ack_o',
        'dcache_flush_ack_o',
        'dcache_mem_req_read_ready_i',
        'dcache_mem_req_read_valid_o',
        'dcache_mem_req_write_data_ready_i',
        'dcache_mem_req_write_data_valid_o',
        'dcache_mem_req_write_ready_i',
        'dcache_mem_req_write_valid_o',
        'dcache_mem_resp_read_ready_o',
        'dcache_mem_resp_read_valid_i',
        'dcache_mem_resp_write_ready_o',
        'dcache_mem_resp_write_valid_i',
        'dcache_read_ready_o',
        'dcache_read_resp_ready_i',
        'dcache_read_resp_valid_o',
        'dcache_read_valid_i',
        'dcache_write_data_ready_o',
        'dcache_write_data_valid_i',
        'dcache_write_ready_o',
        'dcache_write_resp_ready_i',
        'dcache_write_resp_valid_o',
        'dcache_write_valid_i',
        'decoded_instr_ack_i',
        'decoded_instr_ack_o',
        'decoded_instr_valid_i',
        'div_wait_i',
        'done',
        'dside_wait_i',
        'ex_valid_i',
        'ex_valid_o',
        'fetch_entry_ready_i',
        'fetch_entry_ready_o',
        'fetch_entry_valid_i',
        'fetch_entry_valid_o',
        'fetch_stall_o',
        'fetch_valid_i',
        'flu_ready_i',
        'flu_ready_o',
        'flu_valid_o',
        'flush_ack_o',
        'flush_dcache_ack_i',
        'fpu_early_valid_i',
        'fpu_early_valid_o',
        'fpu_ready_i',
        'fpu_ready_o',
        'fpu_valid_i',
        'fpu_valid_o',
        'gnt_i',
        'gnt_o',
        'grant',
        'hpdcache_req_ready_i',
        'hpdcache_req_valid_o',
        'hpdcache_rsp_valid_i',
        'ic_scr_key_valid_i',
        'icache_data_ack_o',
        'icache_miss_ready_o',
        'icache_miss_resp_valid_o',
        'icache_miss_valid_i',
        'id_in_ready_i',
        'id_in_ready_o',
        'if_busy_o',
        'in_valid_i',
        'instr_done_wb_o',
        'instr_gnt_i',
        'instr_id_done_o',
        'instr_valid_clear_i',
        'instr_valid_clear_o',
        'instr_valid_i',
        'instr_valid_id_o',
        'inval_ready_i',
        'inval_ready_o',
        'inval_valid_i',
        'inval_valid_o',
        'iside_wait_i',
        'issue_ack_i',
        'issue_ack_o',
        'issue_entry_valid_o',
        'issue_instr_ack_i',
        'issue_instr_valid_i',
        'issue_instr_valid_o',
        'issue_ready_i',
        'issue_ready_o',
        'issue_stall_o',
        'issue_valid_i',
        'issue_valid_o',
        'load_valid_o',
        'lsu_commit_ready_o',
        'lsu_rdata_valid_o',
        'lsu_ready_i',
        'lsu_ready_o',
        'lsu_req_done_i',
        'lsu_req_done_o',
        'lsu_req_valid_i',
        'lsu_resp_valid_i',
        'lsu_resp_valid_o',
        'lsu_valid_i',
        'lsu_valid_o',
        'mem_data_ack_i',
        'miss_ack_i',
        'miss_ack_o',
        'miss_gnt_i',
        'miss_gnt_o',
        'mul_wait_i',
        'mult_ready_o',
        'mult_valid_i',
        'mult_valid_o',
        'multdiv_ready_id_i',
        'multdiv_ready_id_o',
        'out_ready_i',
        'out_valid_o',
        'perf_div_wait_o',
        'perf_dside_wait_o',
        'perf_mul_wait_o',
        'rd_ack_i',
        'rd_ack_o',
        'rd_gnt_o',
        'rd_valid_o',
        'ready_i',
        'ready_o',
        'ready_wb_i',
        'ready_wb_o',
        'result_ready_o',
        'result_valid_i',
        'rs_valid_i',
        'rvfi_ext_expanded_insn_valid',
        'rvfi_valid',
        'scramble_key_valid_i',
        'stall',
        'stall_i',
        'stall_id_i',
        'stall_issue_i',
        'stall_issue_o',
        'stall_o',
        'stall_st_pending_i',
        'stall_wb_i',
        'store_valid_o',
        'valid',
        'valid_dirty)',
        'valid_i',
        'valid_o',
        'valid_without_flush_i',
        'wr_ack_i',
        'wr_ack_o',
        'wr_gnt_o',
        'wr_valid_o',
        'wt_valid_i',
        'x_commit_valid_o',
        'x_issue_ready_i',
        'x_issue_valid_o',
        'x_ready_o',
        'x_result_ready_o',
        'x_result_valid_i',
        'x_valid_i',
        'x_valid_o',
        'xfu_ready_i',
        'xfu_valid_o'
    ])
    
    # Module type preference
    preferred_module_type: str = "sequential"
    
    def get_info(self) -> Dict:
        """Get pattern information"""
        return {
            'name': self.name,
            'category': self.category,
            'trust_hub_status': self.trust_hub_status,
            'trust_hub_category': self.trust_hub_category,
            'trust_hub_benchmarks': self.trust_hub_benchmarks,
            'trust_hub_source': self.trust_hub_source,
            'rtl_citations': self.rtl_citations,
            'severity': self.severity,
            'description': self.description,
            'adaptation_note': self.adaptation_note,
            'trigger_keywords': self.trigger_keywords,
            'payload_keywords': self.payload_keywords,
            'preferred_module_type': self.preferred_module_type
        }
    
    def get_template_params(self) -> Dict:
        """Get parameters for template generation"""
        return {
            'pattern_name': self.name,
            'description': self.description,
            'trigger_type': 'counter',
            'payload_action': 'periodic_stall_sequential_or_pattern_combinational',
            'delay_cycles': '8',
            'comment_header': f"// Trust-Hub Category: {self.trust_hub_category} (RTL adaptation)\n// Sources: {', '.join(self.rtl_citations[:2])}"
        }


availability_pattern = AvailabilityPattern()


def get_pattern() -> AvailabilityPattern:
    """Get Availability pattern instance"""
    return availability_pattern