#!/usr/bin/env python3
"""
DoS (Denial of Service) Pattern
Based on Trust-Hub Benchmarks: AES-T1800, AES-T1900, AES-T500, BasicRSA-T200

Disables functionality by forcing control signals to 0
"""

from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class DoSPattern:
    """
    Denial of Service Trojan Pattern
    
    Trust-Hub Category: Denial of Service ✓ (Verified)
    Trust-Hub Benchmarks: AES-T1800, AES-T1900, AES-T500, BasicRSA-T200
    Severity: High
    
    Description:
        Disables functionality by forcing critical control signals to 0
        after a specific trigger condition is met. Based on verified
        Trust-Hub RTL benchmarks.
    
    Trust-Hub Mechanism:
        Trust-Hub DoS trojans target cryptographic circuits, causing
        battery drain and resource exhaustion.
    
    RISC-V Adaptation:
        Adapted for processor control signals (enable, valid, ready).
        Targets functional disruption rather than battery drain.
    
    Trigger Mechanism:
        - Counter-based: Activates after N operations
        - Condition-based: Specific input pattern
        - Time-based: After certain clock cycles
    
    Payload:
        Forces control signals (enable, valid, ready) to 0, effectively
        disabling the functionality of the module.
    
    Target Signals:
        - Trigger: enable, valid, start, request signals
        - Payload: enable, valid, ready, start signals (force to 0)
    
    Real-World Impact:
        - System becomes unresponsive
        - Critical operations fail
        - Service denial to legitimate users
    
    Example in RISC-V:
        - Target: ibex_decoder module
        - Signal: instr_valid_o
        - Effect: Prevents instruction execution
    
    References:
        [1] Trust-Hub, "AES-T1800: Denial of Service Trojan"
        [2] Trust-Hub, "AES-T1900: Denial of Service Trojan"
        [3] Trust-Hub, "AES-T500: Denial of Service Trojan"
        [4] Trust-Hub, "BasicRSA-T200: Denial of Service Trojan"
    """
    
    name: str = "DoS"
    category: str = "Denial of Service"
    
    # Trust-Hub verification status
    trust_hub_status: str = "Verified RTL Benchmarks"
    trust_hub_category: str = "Denial of Service"
    trust_hub_benchmarks: str = "AES-T1800, AES-T1900, AES-T500, BasicRSA-T200"
    trust_hub_source: str = "AES-T1800"  # Primary benchmark
    
    # Citations
    rtl_citations: List[str] = field(default_factory=lambda: [
        "Trust-Hub AES-T1800",
        "Trust-Hub AES-T1900",
        "Trust-Hub AES-T500",
        "Trust-Hub BasicRSA-T200"
    ])
    
    # Pattern metadata
    severity: str = "High"
    description: str = "Disables functionality by forcing control signals to 0"
    adaptation_note: str = "Adapted from crypto circuits to RISC-V control signals"
    
    # Keywords for signal matching
    trigger_keywords: List[str] = field(default_factory=lambda: [
        'acc_cons_en_i',
        'acc_cons_en_o',
        'acc_dcache_req_ports_i',
        'acc_dcache_req_ports_o',
        'acc_fflags_ex_valid_i',
        'acc_fflags_valid_o',
        'acc_mmu_en_i',
        'acc_mmu_req_i',
        'acc_mmu_req_o',
        'acc_mmu_req_t',
        'acc_req_o',
        'acc_req_t',
        'acc_valid_ex_o',
        'acc_valid_i',
        'acc_valid_o',
        'active_serving_i',
        'active_serving_o',
        'addr_incr_req_o',
        'aes_valid_i',
        'aes_valid_o',
        'alu2_valid_i',
        'alu2_valid_o',
        'alu_valid_i',
        'alu_valid_o',
        'amo_req_i',
        'amo_req_o',
        'amo_req_t',
        'amo_valid_commit_i',
        'amo_valid_commit_o',
        'ariane_pkg::ad_req_t',
        'ariane_pkg::amo_req_t',
        'axi_req_o',
        'axi_req_t',
        'branch_valid_i',
        'branch_valid_o',
        'break_from_trigger_i',
        'break_from_trigger_o',
        'bypass_valid_i',
        'bypass_valid_o',
        'cache_en_i',
        'cache_en_o',
        'cmo_req_t',
        'commit_lsu_ready_i',
        'commit_ready_o',
        'commit_valid_o',
        'compressed_ready_i',
        'compressed_ready_o',
        'compressed_req_i',
        'compressed_req_o',
        'compressed_valid_i',
        'compressed_valid_o',
        'counter_we_i',
        'counterh_we_i',
        'critical_word_valid_i',
        'critical_word_valid_o',
        'csr_op_en_i',
        'csr_op_en_o',
        'csr_ready_o',
        'csr_valid_i',
        'csr_valid_o',
        'cva6_amo_req_i',
        'cva6_req_i',
        'cva6_req_o',
        'cvxif_ready_i',
        'cvxif_req_i',
        'cvxif_req_o',
        'cvxif_req_t',
        'cvxif_valid_o',
        'data_req_i',
        'data_req_o',
        'data_we_i',
        'data_we_o',
        'dcache_amo_req_i',
        'dcache_cmo_req_i',
        'dcache_data_req_i',
        'dcache_en_o',
        'dcache_enable_i',
        'dcache_mem_req_read_o',
        'dcache_mem_req_read_ready_i',
        'dcache_mem_req_read_valid_o',
        'dcache_mem_req_write_data_o',
        'dcache_mem_req_write_data_ready_i',
        'dcache_mem_req_write_data_valid_o',
        'dcache_mem_req_write_o',
        'dcache_mem_req_write_ready_i',
        'dcache_mem_req_write_valid_o',
        'dcache_mem_resp_read_ready_o',
        'dcache_mem_resp_read_valid_i',
        'dcache_mem_resp_write_ready_o',
        'dcache_mem_resp_write_valid_i',
        'dcache_read_ready_o',
        'dcache_read_resp_ready_i',
        'dcache_read_resp_valid_o',
        'dcache_read_valid_i',
        'dcache_req_i_t',
        'dcache_req_o_t',
        'dcache_req_ports_i',
        'dcache_req_ports_o',
        'dcache_req_t',
        'dcache_write_data_ready_o',
        'dcache_write_data_valid_i',
        'dcache_write_ready_o',
        'dcache_write_resp_ready_i',
        'dcache_write_resp_valid_o',
        'dcache_write_valid_i',
        'debug_from_trigger_i',
        'debug_from_trigger_o',
        'debug_req_i',
        'decoded_instr_valid_i',
        'div_en_ex_o',
        'div_en_i',
        'div_en_o',
        'dummy_instr_en_i',
        'dummy_instr_en_o',
        'dummy_instr_seed_en_i',
        'dummy_instr_seed_en_o',
        'en_g_translation_o',
        'en_i',
        'en_ld_st_g_translation_i',
        'en_ld_st_g_translation_o',
        'en_ld_st_translation_i',
        'en_ld_st_translation_o',
        'en_translation_o',
        'en_wb_i',
        'en_wb_o',
        'enable_g_translation_i',
        'enable_i',
        'enable_translation_i',
        'ex_valid_i',
        'ex_valid_o',
        'fetch_enable_i',
        'fetch_entry_ready_i',
        'fetch_entry_ready_o',
        'fetch_entry_valid_i',
        'fetch_entry_valid_o',
        'fetch_valid_i',
        'flu_ready_i',
        'flu_ready_o',
        'flu_valid_o',
        'fpu_early_valid_i',
        'fpu_early_valid_o',
        'fpu_ready_i',
        'fpu_ready_o',
        'fpu_valid_i',
        'fpu_valid_o',
        'hpdcache_mem_req_t',
        'hpdcache_mem_req_w_t',
        'hpdcache_req_abort_o',
        'hpdcache_req_o',
        'hpdcache_req_pma_o',
        'hpdcache_req_ready_i',
        'hpdcache_req_sid_i',
        'hpdcache_req_sid_t',
        'hpdcache_req_t',
        'hpdcache_req_tag_o',
        'hpdcache_req_valid_o',
        'hpdcache_rsp_valid_i',
        'ibex_pkg::pmp_req_e',
        'ic_data_req_i',
        'ic_data_req_o',
        'ic_scr_key_req_i',
        'ic_scr_key_req_o',
        'ic_scr_key_valid_i',
        'ic_tag_req_i',
        'ic_tag_req_o',
        'icache_data_req_i',
        'icache_en_i',
        'icache_en_o',
        'icache_enable_i',
        'icache_enable_o',
        'icache_miss_ready_o',
        'icache_miss_resp_valid_o',
        'icache_miss_valid_i',
        'icache_req_t',
        'id_in_ready_i',
        'id_in_ready_o',
        'imd_val_we_ex_i',
        'imd_val_we_o',
        'in_valid_i',
        'instr_req_i',
        'instr_req_o',
        'instr_valid_clear_i',
        'instr_valid_clear_o',
        'instr_valid_i',
        'instr_valid_id_o',
        'inval_ready_i',
        'inval_ready_o',
        'inval_valid_i',
        'inval_valid_o',
        'issue_entry_valid_o',
        'issue_instr_valid_i',
        'issue_instr_valid_o',
        'issue_ready_i',
        'issue_ready_o',
        'issue_req_i',
        'issue_req_o',
        'issue_valid_i',
        'issue_valid_o',
        'l15_req_o',
        'l15_req_t',
        'load_valid_o',
        'lsu_addr_incr_req_i',
        'lsu_commit_ready_o',
        'lsu_rdata_valid_o',
        'lsu_ready_i',
        'lsu_ready_o',
        'lsu_req_done_i',
        'lsu_req_done_o',
        'lsu_req_i',
        'lsu_req_o',
        'lsu_req_valid_i',
        'lsu_resp_valid_i',
        'lsu_resp_valid_o',
        'lsu_valid_i',
        'lsu_valid_o',
        'lsu_we_i',
        'lsu_we_o',
        'mem_data_req_o',
        'memory_we',
        'miss_req_i',
        'miss_req_o',
        'miss_req_t',
        'miss_we_i',
        'miss_we_o',
        'mult_en_ex_o',
        'mult_en_i',
        'mult_en_o',
        'mult_ready_o',
        'mult_valid_i',
        'mult_valid_o',
        'multdiv_ready_id_i',
        'multdiv_ready_id_o',
        'noc_req_o',
        'noc_req_t',
        'out_ready_i',
        'out_valid_o',
        'perf_we_o',
        'pmp_req_addr_i',
        'pmp_req_err_o',
        'pmp_req_type_i',
        'rd_req_i',
        'rd_req_o',
        'rd_valid_o',
        'ready_i',
        'ready_o',
        'ready_wb_i',
        'ready_wb_o',
        'req',
        'req_i',
        'req_o',
        'req_port_i',
        'req_port_i.data_rvalid',
        'req_port_o',
        'req_ports_i',
        'req_ports_o',
        'req_t',
        'request',
        'result_ready_o',
        'result_valid_i',
        'rf_we_id_i',
        'rf_we_id_o',
        'rf_we_lsu_i',
        'rf_we_o',
        'rf_we_wb_i',
        'rf_we_wb_o',
        'rs_valid_i',
        'rvfi_ext_expanded_insn_valid',
        'rvfi_valid',
        'scramble_key_valid_i',
        'scramble_req_o',
        'store_valid_o',
        'tdata1_we',
        'tdata2_we',
        'tdata3_we',
        'test_en_i',
        'translation_req_o',
        'trigger_match_i',
        'trigger_match_o',
        'tselect_we',
        'valid',
        'valid_dirty)',
        'valid_i',
        'valid_o',
        'valid_without_flush_i',
        'we',
        'we_a_i',
        'we_fpr_i',
        'we_fpr_o',
        'we_gpr_i',
        'we_gpr_o',
        'we_i',
        'we_o',
        'wr_cl_we_i',
        'wr_cl_we_o',
        'wr_en_i',
        'wr_req_i',
        'wr_req_o',
        'wr_valid_o',
        'wt_valid_i',
        'x_commit_valid_o',
        'x_compressed_req_t',
        'x_issue_ready_i',
        'x_issue_req_o',
        'x_issue_req_t',
        'x_issue_valid_o',
        'x_ready_o',
        'x_result_ready_o',
        'x_result_valid_i',
        'x_valid_i',
        'x_valid_o',
        'x_we_i',
        'x_we_o',
        'xfu_ready_i',
        'xfu_valid_o'
    ])
    
    payload_keywords: List[str] = field(default_factory=lambda: [
        'acc_cons_en_i',
        'acc_cons_en_o',
        'acc_dcache_req_ports_i',
        'acc_dcache_req_ports_o',
        'acc_fflags_ex_valid_i',
        'acc_fflags_valid_o',
        'acc_mmu_en_i',
        'acc_mmu_req_i',
        'acc_mmu_req_o',
        'acc_mmu_req_t',
        'acc_req_o',
        'acc_req_t',
        'acc_valid_ex_o',
        'acc_valid_i',
        'acc_valid_o',
        'active_serving_i',
        'active_serving_o',
        'addr_incr_req_o',
        'aes_valid_i',
        'aes_valid_o',
        'alu2_valid_i',
        'alu2_valid_o',
        'alu_valid_i',
        'alu_valid_o',
        'amo_req_i',
        'amo_req_o',
        'amo_req_t',
        'amo_valid_commit_i',
        'amo_valid_commit_o',
        'ariane_pkg::ad_req_t',
        'ariane_pkg::amo_req_t',
        'axi_req_o',
        'axi_req_t',
        'branch_valid_i',
        'branch_valid_o',
        'bypass_valid_i',
        'bypass_valid_o',
        'cache_en_i',
        'cache_en_o',
        'cmo_req_t',
        'commit_lsu_ready_i',
        'commit_ready_o',
        'commit_valid_o',
        'compressed_ready_i',
        'compressed_ready_o',
        'compressed_req_i',
        'compressed_req_o',
        'compressed_valid_i',
        'compressed_valid_o',
        'counter_we_i',
        'counterh_we_i',
        'critical_word_valid_i',
        'critical_word_valid_o',
        'csr_op_en_i',
        'csr_op_en_o',
        'csr_ready_o',
        'csr_valid_i',
        'csr_valid_o',
        'cva6_amo_req_i',
        'cva6_req_i',
        'cva6_req_o',
        'cvxif_ready_i',
        'cvxif_req_i',
        'cvxif_req_o',
        'cvxif_req_t',
        'cvxif_valid_o',
        'data_req_i',
        'data_req_o',
        'data_we_i',
        'data_we_o',
        'dcache_amo_req_i',
        'dcache_cmo_req_i',
        'dcache_data_req_i',
        'dcache_en_o',
        'dcache_enable_i',
        'dcache_mem_req_read_o',
        'dcache_mem_req_read_ready_i',
        'dcache_mem_req_read_valid_o',
        'dcache_mem_req_write_data_o',
        'dcache_mem_req_write_data_ready_i',
        'dcache_mem_req_write_data_valid_o',
        'dcache_mem_req_write_o',
        'dcache_mem_req_write_ready_i',
        'dcache_mem_req_write_valid_o',
        'dcache_mem_resp_read_ready_o',
        'dcache_mem_resp_read_valid_i',
        'dcache_mem_resp_write_ready_o',
        'dcache_mem_resp_write_valid_i',
        'dcache_read_ready_o',
        'dcache_read_resp_ready_i',
        'dcache_read_resp_valid_o',
        'dcache_read_valid_i',
        'dcache_req_i_t',
        'dcache_req_o_t',
        'dcache_req_ports_i',
        'dcache_req_ports_o',
        'dcache_req_t',
        'dcache_write_data_ready_o',
        'dcache_write_data_valid_i',
        'dcache_write_ready_o',
        'dcache_write_resp_ready_i',
        'dcache_write_resp_valid_o',
        'dcache_write_valid_i',
        'debug_req_i',
        'decoded_instr_valid_i',
        'div_en_ex_o',
        'div_en_i',
        'div_en_o',
        'done',
        'dummy_instr_en_i',
        'dummy_instr_en_o',
        'dummy_instr_seed_en_i',
        'dummy_instr_seed_en_o',
        'en_g_translation_o',
        'en_i',
        'en_ld_st_g_translation_i',
        'en_ld_st_g_translation_o',
        'en_ld_st_translation_i',
        'en_ld_st_translation_o',
        'en_translation_o',
        'en_wb_i',
        'en_wb_o',
        'enable_g_translation_i',
        'enable_i',
        'enable_translation_i',
        'ex_valid_i',
        'ex_valid_o',
        'fetch_enable_i',
        'fetch_entry_ready_i',
        'fetch_entry_ready_o',
        'fetch_entry_valid_i',
        'fetch_entry_valid_o',
        'fetch_valid_i',
        'flu_ready_i',
        'flu_ready_o',
        'flu_valid_o',
        'fpu_early_valid_i',
        'fpu_early_valid_o',
        'fpu_ready_i',
        'fpu_ready_o',
        'fpu_valid_i',
        'fpu_valid_o',
        'hpdcache_mem_req_t',
        'hpdcache_mem_req_w_t',
        'hpdcache_req_abort_o',
        'hpdcache_req_o',
        'hpdcache_req_pma_o',
        'hpdcache_req_ready_i',
        'hpdcache_req_sid_i',
        'hpdcache_req_sid_t',
        'hpdcache_req_t',
        'hpdcache_req_tag_o',
        'hpdcache_req_valid_o',
        'hpdcache_rsp_valid_i',
        'ibex_pkg::pmp_req_e',
        'ic_data_req_i',
        'ic_data_req_o',
        'ic_scr_key_req_i',
        'ic_scr_key_req_o',
        'ic_scr_key_valid_i',
        'ic_tag_req_i',
        'ic_tag_req_o',
        'icache_data_req_i',
        'icache_en_i',
        'icache_en_o',
        'icache_enable_i',
        'icache_enable_o',
        'icache_miss_ready_o',
        'icache_miss_resp_valid_o',
        'icache_miss_valid_i',
        'icache_req_t',
        'id_in_ready_i',
        'id_in_ready_o',
        'imd_val_we_ex_i',
        'imd_val_we_o',
        'in_valid_i',
        'instr_done_wb_o',
        'instr_id_done_o',
        'instr_req_i',
        'instr_req_o',
        'instr_valid_clear_i',
        'instr_valid_clear_o',
        'instr_valid_i',
        'instr_valid_id_o',
        'inval_ready_i',
        'inval_ready_o',
        'inval_valid_i',
        'inval_valid_o',
        'issue_entry_valid_o',
        'issue_instr_valid_i',
        'issue_instr_valid_o',
        'issue_ready_i',
        'issue_ready_o',
        'issue_req_i',
        'issue_req_o',
        'issue_valid_i',
        'issue_valid_o',
        'l15_req_o',
        'l15_req_t',
        'load_valid_o',
        'lsu_addr_incr_req_i',
        'lsu_commit_ready_o',
        'lsu_rdata_valid_o',
        'lsu_ready_i',
        'lsu_ready_o',
        'lsu_req_done_i',
        'lsu_req_done_o',
        'lsu_req_i',
        'lsu_req_o',
        'lsu_req_valid_i',
        'lsu_resp_valid_i',
        'lsu_resp_valid_o',
        'lsu_valid_i',
        'lsu_valid_o',
        'lsu_we_i',
        'lsu_we_o',
        'mem_data_req_o',
        'memory_we',
        'miss_req_i',
        'miss_req_o',
        'miss_req_t',
        'miss_we_i',
        'miss_we_o',
        'mult_en_ex_o',
        'mult_en_i',
        'mult_en_o',
        'mult_ready_o',
        'mult_valid_i',
        'mult_valid_o',
        'multdiv_ready_id_i',
        'multdiv_ready_id_o',
        'noc_req_o',
        'noc_req_t',
        'out_ready_i',
        'out_valid_o',
        'perf_we_o',
        'pmp_req_addr_i',
        'pmp_req_err_o',
        'pmp_req_type_i',
        'rd_req_i',
        'rd_req_o',
        'rd_valid_o',
        'ready_i',
        'ready_o',
        'ready_wb_i',
        'ready_wb_o',
        'req',
        'req_i',
        'req_o',
        'req_port_i',
        'req_port_i.data_rvalid',
        'req_port_o',
        'req_ports_i',
        'req_ports_o',
        'req_t',
        'result_ready_o',
        'result_valid_i',
        'rf_we_id_i',
        'rf_we_id_o',
        'rf_we_lsu_i',
        'rf_we_o',
        'rf_we_wb_i',
        'rf_we_wb_o',
        'rs_valid_i',
        'rvfi_ext_expanded_insn_valid',
        'rvfi_valid',
        'scramble_key_valid_i',
        'scramble_req_o',
        'store_valid_o',
        'tdata1_we',
        'tdata2_we',
        'tdata3_we',
        'test_en_i',
        'translation_req_o',
        'tselect_we',
        'valid',
        'valid_dirty)',
        'valid_i',
        'valid_o',
        'valid_without_flush_i',
        'we',
        'we_a_i',
        'we_fpr_i',
        'we_fpr_o',
        'we_gpr_i',
        'we_gpr_o',
        'we_i',
        'we_o',
        'wr_cl_we_i',
        'wr_cl_we_o',
        'wr_en_i',
        'wr_req_i',
        'wr_req_o',
        'wr_valid_o',
        'wt_valid_i',
        'x_commit_valid_o',
        'x_compressed_req_t',
        'x_issue_ready_i',
        'x_issue_req_o',
        'x_issue_req_t',
        'x_issue_valid_o',
        'x_ready_o',
        'x_result_ready_o',
        'x_result_valid_i',
        'x_valid_i',
        'x_valid_o',
        'x_we_i',
        'x_we_o',
        'xfu_ready_i',
        'xfu_valid_o'
    ])
    
    # Module type preference
    preferred_module_type: str = "sequential"  # Can work with both
    
    def get_info(self) -> Dict:
        """Get pattern information as dictionary"""
        return {
            'name': self.name,
            'category': self.category,
            'trust_hub_status': self.trust_hub_status,
            'trust_hub_category': self.trust_hub_category,
            'trust_hub_benchmarks': self.trust_hub_benchmarks,
            'trust_hub_source': self.trust_hub_source,
            'rtl_citations': self.rtl_citations,
            'severity': self.severity,
            'description': self.description,
            'adaptation_note': self.adaptation_note,
            'trigger_keywords': self.trigger_keywords,
            'payload_keywords': self.payload_keywords,
            'preferred_module_type': self.preferred_module_type
        }
    
    def get_template_params(self) -> Dict:
        """Get parameters for template generation"""
        return {
            'pattern_name': self.name,
            'description': self.description,
            'trigger_type': 'counter',  # or 'condition'
            'payload_action': 'disable',
            'default_counter_value': '32\'hFFFF',
            'comment_header': f"// Trust-Hub {self.trust_hub_benchmarks}: {self.category}"
        }


# Create default instance
dos_pattern = DoSPattern()


def get_pattern() -> DoSPattern:
    """Get DoS pattern instance"""
    return dos_pattern