#!/usr/bin/env python3
"""
Information Leakage Pattern
Based on Trust-Hub Benchmarks: AES-T600, AES-T1400, AES-T800

Leaks sensitive data to attacker-accessible locations
"""

from dataclasses import dataclass, field
from typing import List, Dict


@dataclass
class LeakPattern:
    """
    Information Leakage Trojan Pattern
    
    Trust-Hub Category: Leak Information ✓ (Verified)
    Trust-Hub Benchmarks: AES-T600, AES-T1400, AES-T800
    Severity: Critical
    
    Description:
        Leaks sensitive data (keys, secrets, addresses) to attacker-accessible
        locations such as unused ports, debug interfaces, or observable channels.
        Based on verified Trust-Hub RTL benchmarks.
    
    Trust-Hub Mechanism:
        Trust-Hub leak trojans use side-channel methods (power, current)
        to exfiltrate cryptographic keys from AES circuits.
    
    RISC-V Adaptation:
        Adapted to route processor secrets (CSR contents, privilege data)
        to debug outputs or unused ports for direct leakage.
    
    Trigger Mechanism:
        - Debug mode activation
        - External pin signal
        - Specific operational mode
        - Test mode enabled
    
    Payload:
        Routes secret data to unused output ports, debug interfaces, or
        creates observable side channels.
    
    Target Signals:
        - Trigger: debug, test, mode, external control signals
        - Payload: key, secret, data, addr, address, priv signals
    
    Real-World Impact:
        - Cryptographic key exposure
        - Privileged information leak
        - Address space disclosure
        - Security bypass
    
    Example in RISC-V:
        - Target: ibex_cs_registers module
        - Signal: csr_rdata_o
        - Effect: Leaks CSR contents to unused debug port
    
    References:
        [1] Trust-Hub, "AES-T600: Information Leakage Trojan"
        [2] Trust-Hub, "AES-T1400: Information Leakage Trojan"
        [3] Trust-Hub, "AES-T800: Information Leakage Trojan"
    """
    
    name: str = "Leak"
    category: str = "Information Leakage"
    
    # Trust-Hub verification status
    trust_hub_status: str = "Verified RTL Benchmarks"
    trust_hub_category: str = "Leak Information"
    trust_hub_benchmarks: str = "AES-T600, AES-T1400, AES-T800"
    trust_hub_source: str = "AES-T600"  # Primary benchmark
    
    # Citations
    rtl_citations: List[str] = field(default_factory=lambda: [
        "Trust-Hub AES-T600",
        "Trust-Hub AES-T1400",
        "Trust-Hub AES-T800"
    ])
    
    # Pattern metadata
    severity: str = "Critical"
    description: str = "Leaks sensitive data to attacker-accessible location"
    adaptation_note: str = "Adapted from power side-channels to direct CSR leakage"
    
    # Keywords for signal matching
    trigger_keywords: List[str] = field(default_factory=lambda: [
        'RSD_DISABLE_DEBUG_REGISTER',
        'Rounding_Mode',
        'WRITE_NUM',
        'commit_csr_o',
        'conf_addr_mode_i',
        'counter_we_i',
        'counterh_we_i',
        'csr_access_i',
        'csr_access_o',
        'csr_addr)',
        'csr_addr_i',
        'csr_addr_o',
        'csr_commit_i',
        'csr_depc_i',
        'csr_depc_o',
        'csr_exception_i',
        'csr_exception_o',
        'csr_hs_ld_st_inst_i',
        'csr_hs_ld_st_inst_o',
        'csr_i',
        'csr_mcause_i',
        'csr_mepc_i',
        'csr_mepc_o',
        'csr_mstatus_mie_i',
        'csr_mstatus_mie_o',
        'csr_mstatus_tw_i',
        'csr_mstatus_tw_o',
        'csr_mtval_i',
        'csr_mtval_o',
        'csr_mtvec_i',
        'csr_mtvec_init_i',
        'csr_mtvec_init_o',
        'csr_mtvec_o',
        'csr_op_en_i',
        'csr_op_en_o',
        'csr_op_i',
        'csr_op_o',
        'csr_pipe_flush_i',
        'csr_pmp_addr_i',
        'csr_pmp_addr_o',
        'csr_pmp_cfg_i',
        'csr_pmp_cfg_o',
        'csr_pmp_mseccfg_i',
        'csr_pmp_mseccfg_o',
        'csr_rdata_i',
        'csr_rdata_o',
        'csr_ready_o',
        'csr_restore_dret_i',
        'csr_restore_dret_id_o',
        'csr_restore_mret_i',
        'csr_restore_mret_id_o',
        'csr_result_o',
        'csr_save_cause_i',
        'csr_save_cause_o',
        'csr_save_id_i',
        'csr_save_id_o',
        'csr_save_if_i',
        'csr_save_if_o',
        'csr_save_wb_i',
        'csr_save_wb_o',
        'csr_shadow_err_o',
        'csr_valid_i',
        'csr_valid_o',
        'csr_wdata_i',
        'csr_wdata_o',
        'csr_write_fflags_i',
        'csr_write_fflags_o',
        'data_we_i',
        'data_we_o',
        'dcache_mem_req_write_data_o',
        'dcache_mem_req_write_data_ready_i',
        'dcache_mem_req_write_data_valid_o',
        'dcache_mem_req_write_o',
        'dcache_mem_req_write_ready_i',
        'dcache_mem_req_write_valid_o',
        'dcache_mem_resp_write_i',
        'dcache_mem_resp_write_ready_o',
        'dcache_mem_resp_write_valid_i',
        'dcache_write_data_i',
        'dcache_write_data_ready_o',
        'dcache_write_data_valid_i',
        'dcache_write_i',
        'dcache_write_ready_o',
        'dcache_write_resp_o',
        'dcache_write_resp_ready_i',
        'dcache_write_resp_valid_o',
        'dcache_write_valid_i',
        'debug_cause_i',
        'debug_cause_o',
        'debug_csr_save_i',
        'debug_csr_save_o',
        'debug_ebreakm_i',
        'debug_ebreakm_o',
        'debug_ebreaku_i',
        'debug_ebreaku_o',
        'debug_from_mcontrol_o',
        'debug_from_trigger_i',
        'debug_from_trigger_o',
        'debug_mode_entering_i',
        'debug_mode_entering_o',
        'debug_mode_i',
        'debug_mode_o',
        'debug_req_i',
        'debug_single_step_i',
        'debug_single_step_o',
        'flush_csr_i',
        'halt_csr_i',
        'halt_csr_o',
        'ic_data_write_i',
        'ic_data_write_o',
        'ic_tag_write_i',
        'ic_tag_write_o',
        'illegal_csr_insn_i',
        'illegal_csr_insn_o',
        'imd_val_we_ex_i',
        'imd_val_we_o',
        'lsu_we_i',
        'lsu_we_o',
        'memory_we',
        'miss_we_i',
        'miss_we_o',
        'mode',
        'multdiv_signed_mode_ex_o',
        'multdiv_signed_mode_i',
        'multdiv_signed_mode_o',
        'nmi_mode_i',
        'nmi_mode_o',
        'perf_we_o',
        'priv_mode_i',
        'priv_mode_id_o',
        'priv_mode_lsu_o',
        'rf_we_id_i',
        'rf_we_id_o',
        'rf_we_lsu_i',
        'rf_we_o',
        'rf_we_wb_i',
        'rf_we_wb_o',
        'rf_write_wb_i',
        'rf_write_wb_o',
        'riscv::pmp_addr_mode_t',
        'rvfi_csr_o',
        'rvfi_csr_t',
        'rvfi_mode',
        'rvfi_probes_csr_t',
        'set_debug_pc_i',
        'set_debug_pc_o',
        'signed_mode_i',
        'tdata1_we',
        'tdata2_we',
        'tdata3_we',
        'test_en_i',
        'tselect_we',
        'we',
        'we_a_i',
        'we_fpr_i',
        'we_fpr_o',
        'we_gpr_i',
        'we_gpr_o',
        'we_i',
        'we_o',
        'wr_cl_we_i',
        'wr_cl_we_o',
        'write',
        'writeIndex',
        'x_we_i',
        'x_we_o'
    ])
    
    payload_keywords: List[str] = field(default_factory=lambda: [
        'ISSUE_QUEUE_SRC_REG_NUM',
        'ISSUE_QUEUE_SRC_REG_NUM-1:0',
        'RSD_DISABLE_DEBUG_REGISTER',
        '`PS_PL_CTRL_QUEUE_DATA_BIT_SIZE-1:0',
        'acc_result_o',
        'adder_result_ex_i',
        'adder_result_ext_o',
        'adder_result_o',
        'addr',
        'addr_i',
        'addr_incr_req_o',
        'addr_last_o',
        'addr_o',
        'address_i',
        'alu_adder_result_ex_o',
        'alu_operand_a_ex_o',
        'alu_operand_a_i',
        'alu_operand_a_o',
        'alu_operand_b_ex_o',
        'alu_operand_b_i',
        'alu_operand_b_o',
        'amo_operand_a_i',
        'amo_operand_b_i',
        'amo_result_o',
        'axi_data_i',
        'axi_data_o',
        'boot_addr_i',
        'branch_result_o',
        'bt_a_operand_i',
        'bt_a_operand_o',
        'bt_b_operand_i',
        'bt_b_operand_o',
        'bypass_data_i',
        'bypass_data_o',
        'commit_csr_o',
        'comparison_result_o',
        'conf_addr_i',
        'conf_addr_mode_i',
        'conf_addr_prev_i',
        'csr_access_i',
        'csr_access_o',
        'csr_addr)',
        'csr_addr_i',
        'csr_addr_o',
        'csr_commit_i',
        'csr_depc_i',
        'csr_depc_o',
        'csr_exception_i',
        'csr_exception_o',
        'csr_hs_ld_st_inst_i',
        'csr_hs_ld_st_inst_o',
        'csr_i',
        'csr_mcause_i',
        'csr_mepc_i',
        'csr_mepc_o',
        'csr_mstatus_mie_i',
        'csr_mstatus_mie_o',
        'csr_mstatus_tw_i',
        'csr_mstatus_tw_o',
        'csr_mtval_i',
        'csr_mtval_o',
        'csr_mtvec_i',
        'csr_mtvec_init_i',
        'csr_mtvec_init_o',
        'csr_mtvec_o',
        'csr_op_en_i',
        'csr_op_en_o',
        'csr_op_i',
        'csr_op_o',
        'csr_pipe_flush_i',
        'csr_pmp_addr_i',
        'csr_pmp_addr_o',
        'csr_pmp_cfg_i',
        'csr_pmp_cfg_o',
        'csr_pmp_mseccfg_i',
        'csr_pmp_mseccfg_o',
        'csr_rdata_i',
        'csr_rdata_o',
        'csr_ready_o',
        'csr_restore_dret_i',
        'csr_restore_dret_id_o',
        'csr_restore_mret_i',
        'csr_restore_mret_id_o',
        'csr_result_o',
        'csr_save_cause_i',
        'csr_save_cause_o',
        'csr_save_id_i',
        'csr_save_id_o',
        'csr_save_if_i',
        'csr_save_if_o',
        'csr_save_wb_i',
        'csr_save_wb_o',
        'csr_shadow_err_o',
        'csr_valid_i',
        'csr_valid_o',
        'csr_wdata_i',
        'csr_wdata_o',
        'csr_write_fflags_i',
        'csr_write_fflags_o',
        'data',
        'dataIn',
        'dataOut',
        'data_addr_i',
        'data_addr_o',
        'data_be_i',
        'data_be_o',
        'data_bus_err_i',
        'data_err_i',
        'data_gnt_i',
        'data_i',
        'data_ind_timing_i',
        'data_ind_timing_o',
        'data_o',
        'data_pmp_err_i',
        'data_rdata_i',
        'data_rdata_intg_i',
        'data_req_i',
        'data_req_o',
        'data_rvalid_i',
        'data_sign_extension_o',
        'data_size_i',
        'data_type_o',
        'data_wdata_i',
        'data_wdata_intg_o',
        'data_wdata_o',
        'data_we_i',
        'data_we_o',
        'dcache_data_ack_o',
        'dcache_data_i',
        'dcache_data_req_i',
        'dcache_mem_req_write_data_o',
        'dcache_mem_req_write_data_ready_i',
        'dcache_mem_req_write_data_valid_o',
        'dcache_write_data_i',
        'dcache_write_data_ready_o',
        'dcache_write_data_valid_i',
        'debug_csr_save_i',
        'debug_csr_save_o',
        'dummy_instr_data_o',
        'exception_addr_i',
        'fetch_rdata_i',
        'flu_result_o',
        'flush_csr_i',
        'fma_result',
        'fpu_result_o',
        'fu_data_cpop_i',
        'fu_data_i',
        'fu_data_o',
        'fu_data_t',
        'halt_csr_i',
        'halt_csr_o',
        'ic_data_addr_i',
        'ic_data_addr_o',
        'ic_data_rdata_i',
        'ic_data_req_i',
        'ic_data_req_o',
        'ic_data_wdata_i',
        'ic_data_wdata_o',
        'ic_data_write_i',
        'ic_data_write_o',
        'ic_tag_addr_i',
        'ic_tag_addr_o',
        'ic_tag_rdata_i',
        'ic_tag_wdata_i',
        'ic_tag_wdata_o',
        'icache_data_ack_o',
        'icache_data_i',
        'icache_data_req_i',
        'illegal_csr_insn_i',
        'illegal_csr_insn_o',
        'in_addr_i',
        'in_rdata_i',
        'instr_addr_i',
        'instr_addr_o',
        'instr_rdata_alu_i',
        'instr_rdata_alu_id_o',
        'instr_rdata_c_i',
        'instr_rdata_c_id_o',
        'instr_rdata_i',
        'instr_rdata_id_o',
        'instr_rdata_intg_i',
        'inval_addr_i',
        'inval_addr_o',
        'is_equal_result_o',
        'jump_address_i',
        'jump_address_o',
        'l_data_t',
        'load_result_o',
        'lsu_addr_incr_req_i',
        'lsu_addr_last_i',
        'lsu_rdata_o',
        'lsu_rdata_valid_o',
        'lsu_wdata_i',
        'lsu_wdata_o',
        'mem_data_ack_i',
        'mem_data_o',
        'mem_data_req_o',
        'memory_addr',
        'memory_data',
        'miss_wdata_i',
        'miss_wdata_o',
        'mshr_addr_i',
        'mshr_addr_matches_i',
        'mshr_addr_matches_o',
        'mshr_addr_o',
        'multdiv_operand_a_ex_o',
        'multdiv_operand_a_i',
        'multdiv_operand_b_ex_o',
        'multdiv_operand_b_i',
        'multdiv_result_o',
        'nt_branch_addr_i',
        'nt_branch_addr_o',
        'operand_a_i',
        'operand_b_i',
        'out',
        'out_addr_o',
        'out_err_o',
        'out_err_plus2_o',
        'out_rdata_o',
        'out_rdy_i',
        'out_ready_i',
        'out_valid_o',
        'out_vld_o',
        'perf_addr_o',
        'perf_data_i',
        'perf_data_o',
        'pmp_req_addr_i',
        'predict_address_i',
        'ram_cfg_icache_data_i',
        'ram_cfg_rsp_icache_data_o',
        'rd_addr_i',
        'rd_data_i',
        'rd_data_o',
        'rdata_a_o',
        'rdata_b_o',
        'rdata_i',
        'rdata_o',
        'replay_addr_o',
        'req_port_i.data_rvalid',
        'result',
        'result_ex_i',
        'result_ex_o',
        'result_i',
        'result_o',
        'result_ready_o',
        'result_valid_i',
        'rf_rdata_a_ecc_i',
        'rf_rdata_a_i',
        'rf_rdata_b_ecc_i',
        'rf_rdata_b_i',
        'rf_wdata_fwd_wb_i',
        'rf_wdata_fwd_wb_o',
        'rf_wdata_id_i',
        'rf_wdata_id_o',
        'rf_wdata_lsu_i',
        'rf_wdata_sel_o',
        'rf_wdata_wb_ecc_i',
        'rf_wdata_wb_o',
        'riscv::pmp_addr_mode_t',
        'rvfi_csr_o',
        'rvfi_csr_t',
        'rvfi_mem_addr',
        'rvfi_mem_rdata',
        'rvfi_mem_wdata',
        'rvfi_pc_rdata',
        'rvfi_pc_wdata',
        'rvfi_probes_csr_t',
        'rvfi_rd_addr',
        'rvfi_rd_wdata',
        'rvfi_rs1_addr',
        'rvfi_rs1_rdata',
        'rvfi_rs2_addr',
        'rvfi_rs2_rdata',
        'rvfi_rs3_addr',
        'rvfi_rs3_rdata',
        'store_result_i',
        'store_result_o',
        'wbuffer_data_i',
        'wbuffer_data_o',
        'wdata_a_i',
        'wdata_i',
        'wdata_o',
        'wr_addr_i',
        'wr_cl_data_be_i',
        'wr_cl_data_be_o',
        'wr_cl_data_i',
        'wr_cl_data_o',
        'wr_data_be_i',
        'wr_data_be_o',
        'wr_data_i',
        'wr_data_o',
        'x_result_i',
        'x_result_o',
        'x_result_ready_o',
        'x_result_t',
        'x_result_valid_i'
    ])
    
    # Module type preference
    preferred_module_type: str = "both"
    
    def get_info(self) -> Dict:
        """Get pattern information"""
        return {
            'name': self.name,
            'category': self.category,
            'trust_hub_status': self.trust_hub_status,
            'trust_hub_category': self.trust_hub_category,
            'trust_hub_benchmarks': self.trust_hub_benchmarks,
            'trust_hub_source': self.trust_hub_source,
            'rtl_citations': self.rtl_citations,
            'severity': self.severity,
            'description': self.description,
            'adaptation_note': self.adaptation_note,
            'trigger_keywords': self.trigger_keywords,
            'payload_keywords': self.payload_keywords,
            'preferred_module_type': self.preferred_module_type
        }
    
    def get_template_params(self) -> Dict:
        """Get parameters for template generation"""
        return {
            'pattern_name': self.name,
            'description': self.description,
            'trigger_type': 'signal',
            'payload_action': 'leak',
            'leak_destination': 'debug_port',
            'comment_header': f"// Trust-Hub {self.trust_hub_benchmarks}: {self.category}"
        }


leak_pattern = LeakPattern()


def get_pattern() -> LeakPattern:
    """Get Leak pattern instance"""
    return leak_pattern
