"""
Testbench Generator for Hardware Modules
Automatically creates basic testbenches for RTL modules
"""

from pathlib import Path
from src.parser import RTLParser

class TestbenchGenerator:
    """Generate SystemVerilog testbenches for modules"""
    
    def __init__(self):
        self.clock_period = 10  # ns
        self.reset_cycles = 5
        self.sim_cycles = 1000
        
    def generate_testbench(self, module_file, output_dir=None):
        """
        Generate a basic testbench for a module
        
        Args:
            module_file: Path to RTL module file
            output_dir: Directory to save testbench (default: same as module)
            
        Returns:
            Path to generated testbench file
        """
        # Parse the module
        parser = RTLParser(module_file)
        module = parser.parse()
        
        if not module:
            raise ValueError(f"Could not parse module: {module_file}")
        
        # Generate testbench content
        tb_content = self._generate_tb_content(module)
        
        # Determine output path
        if output_dir is None:
            output_dir = Path(module_file).parent
        else:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)
        
        tb_filename = f"tb_{module.name}.sv"
        tb_path = output_dir / tb_filename
        
        # Write testbench
        with open(tb_path, 'w') as f:
            f.write(tb_content)
        
        return str(tb_path)
    
    def _generate_tb_content(self, module):
        """Generate testbench SystemVerilog code"""
        
        # Find clock and reset signals
        clock_signal = self._find_clock_signal(module)
        reset_signal = self._find_reset_signal(module)
        
        # Start generating testbench
        lines = []
        lines.append(f"// Testbench for {module.name}")
        lines.append(f"// Auto-generated by RV-TroGen")
        lines.append(f"")
        lines.append(f"module tb_{module.name};")
        lines.append(f"")
        
        # Declare signals
        lines.append(f"    // Clock and reset")
        if clock_signal:
            lines.append(f"    logic {clock_signal} = 0;")
        if reset_signal:
            lines.append(f"    logic {reset_signal} = 0;")
        lines.append(f"")
        
        lines.append(f"    // Input signals")
        for sig in module.inputs:
            if sig.name not in [clock_signal, reset_signal]:
                width = f"[{sig.width-1}:0] " if sig.width > 1 else ""
                lines.append(f"    logic {width}{sig.name} = 0;")
        lines.append(f"")
        
        lines.append(f"    // Output signals")
        for sig in module.outputs:
            width = f"[{sig.width-1}:0] " if sig.width > 1 else ""
            lines.append(f"    logic {width}{sig.name};")
        lines.append(f"")
        
        # Clock generation
        if clock_signal:
            lines.append(f"    // Clock generation ({self.clock_period}ns period)")
            lines.append(f"    always #{self.clock_period/2} {clock_signal} = ~{clock_signal};")
            lines.append(f"")
        
        # DUT instantiation
        lines.append(f"    // Device Under Test")
        lines.append(f"    {module.name} dut (")
        
        # Port connections
        port_connections = []
        for sig in module.inputs + module.outputs:
            port_connections.append(f"        .{sig.name}({sig.name})")
        lines.append(",\n".join(port_connections))
        lines.append(f"    );")
        lines.append(f"")
        
        # Test stimulus
        lines.append(f"    // Test stimulus")
        lines.append(f"    initial begin")
        
        # VCD dump
        lines.append(f"        // VCD dump for waveform viewing")
        lines.append(f"        $dumpfile(\"tb_{module.name}.vcd\");")
        lines.append(f"        $dumpvars(0, tb_{module.name});")
        lines.append(f"")
        
        # Reset sequence
        if reset_signal:
            lines.append(f"        // Reset sequence")
            lines.append(f"        {reset_signal} = 0;")
            lines.append(f"        repeat({self.reset_cycles}) @(posedge {clock_signal});")
            lines.append(f"        {reset_signal} = 1;")
            lines.append(f"        repeat(2) @(posedge {clock_signal});")
            lines.append(f"")
        
        # Stimulus
        lines.append(f"        // Apply test stimulus")
        lines.append(f"        // TODO: Add specific test patterns")
        lines.append(f"")
        
        # Run simulation
        lines.append(f"        // Run simulation")
        lines.append(f"        repeat({self.sim_cycles}) @(posedge {clock_signal});")
        lines.append(f"")
        
        lines.append(f"        // End simulation")
        lines.append(f"        $display(\"Simulation completed at time %0t\", $time);")
        lines.append(f"        $finish;")
        lines.append(f"    end")
        lines.append(f"")
        
        # Timeout watchdog
        lines.append(f"    // Timeout watchdog")
        lines.append(f"    initial begin")
        lines.append(f"        #{self.sim_cycles * self.clock_period * 2} $fatal(\"Simulation timeout!\");")
        lines.append(f"    end")
        lines.append(f"")
        
        lines.append(f"endmodule")
        
        return "\n".join(lines)
    
    def _find_clock_signal(self, module):
        """Find clock signal (clk, clk_i, clock, etc.)"""
        clock_names = ['clk', 'clk_i', 'clock', 'clk_in']
        for sig in module.inputs:
            if sig.name.lower() in clock_names:
                return sig.name
        return None
    
    def _find_reset_signal(self, module):
        """Find reset signal (rst, rst_n, reset, etc.)"""
        reset_names = ['rst', 'rst_n', 'rst_ni', 'reset', 'reset_n', 'rst_i']
        for sig in module.inputs:
            if sig.name.lower() in reset_names:
                return sig.name
        return None